### ISSUE TITLE
NullReferenceException on Linux server launch

### ISSUE THREAD

**Issue by Simber1** [andruzzzhka/BeatSaberMultiplayer#103]
[This is the error I get](http://prettyawful.net/u/2019-03-28_12-20-32.png)
`
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Lidgren.Network.NetPeer.InitializeNetwork()
   at Lidgren.Network.NetPeer.Start()
   at ServerHub.Hub.HubListener.Start() in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Hub\HubListener.cs:line 82
   at ServerHub.Hub.Program.Start(String[] args) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Hub\Program.cs:line 242
   at ServerHub.Hub.Program.Main(String[] args) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Hub\Program.cs:line 49
`

I get the same error when launching with dotnet ./ServerHub.dll

Distro: Centos 7

**Comment by Simber1** [comment]
Using a new server with Ubuntu 18.04 it works fine.
