### ISSUE TITLE
tem.Net.Http.Native': The specified module or one of its dependencies could not be found.

### ISSUE THREAD

**Issue by Bluscream** [andruzzzhka/BeatSaberMultiplayer#157]
```
blu@minopia:/opt/beatsaber $ ./ServerHub
[LOG       -- 11:44:19] Beat Saber Multiplayer ServerHub v0.6.4.4
[LOG       -- 11:44:19] Found 0 plugins!
[WARNING   -- 11:44:20] Unable to fetch public IP!
[LOG       -- 11:44:20] Hosting ServerHub @ 127.0.0.1:3700
[WARNING   -- 11:44:20] Unable to fetch public IP!
[LOG       -- 11:44:20] Hosting  WebSocket Server @ 127.0.0.1:3701
tem.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at ServerHub.Misc.VersionChecker.Client_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e) in D:\andru\Desktop\BeatSaberMultiplayer-0.6.4.3\ServerHub\Misc\VersionChecker.cs:line 36
```

**Comment by andruzzzhka** [comment]
Try installing `libssl1.0.2` or `libssl1.1`

**Comment by Bluscream** [comment]
```
blu@minopia:~$ sudo apt install libssl1.0.2
[sudo] password for blu:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl1.0.2 is already the newest version (1.0.2s-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
blu@minopia:~$ sudo apt install libssl1.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl1.1 is already the newest version (1.1.1d-0+deb10u2+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by tu0mas** [comment]
same error here

```
user@geko:~/ServerHub$ ./ServerHub
[LOG       -- 13:22:26] Beat Saber Multiplayer ServerHub v0.7.2.1
[LOG       -- 13:22:27] Found 0 plugins!
[EXCEPTION -- 13:22:29] System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Sentry.Internal.Http.DefaultSentryHttpClientFactory.Create(Dsn dsn, SentryOptions options)
   at Sentry.Internal.SdkComposer.CreateBackgroundWorker()
   at Sentry.SentryClient..ctor(SentryOptions options, IBackgroundWorker worker)
   at Sentry.Internal.Hub..ctor(SentryOptions options)
   at Sentry.SentrySdk.Init(SentryOptions options)
   at Sentry.SentrySdk.Init(Action`1 configureOptions)
   at ServerHub.Hub.Program.Start(String[] args)
   at ServerHub.Hub.Program.Main(String[] args)
[LOG       -- 13:22:29] Shutting down...

Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Sentry.Internal.Http.DefaultSentryHttpClientFactory.Create(Dsn dsn, SentryOptions options)
   at Sentry.Internal.SdkComposer.CreateBackgroundWorker()
   at Sentry.SentryClient..ctor(SentryOptions options, IBackgroundWorker worker)
   at Sentry.Internal.Hub..ctor(SentryOptions options)
   at Sentry.SentrySdk.Init(SentryOptions options)
   at Sentry.SentrySdk.Init(Action`1 configureOptions)
   at ServerHub.Hub.Program.Start(String[] args)
   at ServerHub.Hub.Program.Main(String[] args)
Aborted
```

**Comment by senacand** [comment]
Happened to me too. This is because there are missing dependencies.

Use the command `ldd System.Net.Http.Native.so`, check which dependencies are missing, and then install the specified dependencies.

**Comment by tu0mas** [comment]
Thank you. I had to install libcurl3 and remove libcurl4, works like a charm now!
