### ISSUE TITLE
Hubs cease to work after a while.

### ISSUE THREAD

**Issue by joelixny** [andruzzzhka/BeatSaberMultiplayer#45]
I have 2 hubs running, after a while they both stop working, without crashing. They appear as up but stop responding to clients.

They both have an error message as their last output.

5.1.1 from the Releases page:
```
9/16/18 11:53:42 PM|Error|<>c__DisplayClass71_0.<receiveRequest>b__0:850|An exception has occurred while reading an HTTP request/response.
```
5.1.3 that I compiled, from [this commit](https://github.com/lolPants/BeatSaberMultiplayer/commit/64e415aaa5780fe744758daf75f1901116bd597d) 

```
9/16/18 9:54:56 PM|Fatal|<>c__DisplayClass174_0.<startReceiving>b__2:2187|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                            at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header) in D:\Projects\C#\BeatSaber\Source\BeatSaberMultiplayer-rewrite\ServerHub\Websocket-sharp\WebSocketFrame.cs:line 432
                            at WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes) in D:\Projects\C#\BeatSaber\Source\BeatSaberMultiplayer-rewrite\ServerHub\Websocket-sharp\WebSocketFrame.cs:line 529
                            at WebSocketSharp.Ext.<>c__DisplayClass56_0.<ReadBytesAsync>b__0(IAsyncResult ar) in D:\Projects\C#\BeatSaber\Source\BeatSaberMultiplayer-rewrite\ServerHub\Websocket-sharp\Ext.cs:line 761
```

Note that they both happened almost at the exact same time, the first one's clock is 2 hours ahead of the second one's.

**Comment by joelixny** [comment]
I managed to reproduce the second error, it happens when refreshing the WebSockets page while it's still loading. It also appears to be unrelated to the hubs not working, as the hub I tried it on continued to work even after reproducing the error.

**Comment by stewartgill1977** [comment]
Its getting to the point where it's a 24/7 job to keep an eye out and restart the hub when it stops. Its happen so much now that its getting to the point where it just takes up to much time to keep running. ver 0.5.4.2

**Comment by Assistant** [comment]
I've setup automated scripts to detect if a hub has stopped working and restart it. That seems to work pretty well.

**Comment by andruzzzhka** [comment]
Is there a reliable way to reproduce this?

**Comment by stewartgill1977** [comment]
Thanks Assistant for the help last night to set up your scripts. The server now restarts by itself meaning i now don't have to sit here and watch it 24/7 lol. :)

**Comment by stewartgill1977** [comment]
> 
> 
> Is there a reliable way to reproduce this?
> Server freezes or crashes?

not that i know of it just does it at random. Some times it would run for hours other times 5mins and then need a manual restart.
