### ISSUE TITLE
destroyempty command does not work

### ISSUE THREAD

**Issue by Assistant** [andruzzzhka/BeatSaberMultiplayer#46]
When attempting to use the command it will destroy the first empty room and then fail with a message like this one:
```
[LOG       -- 06:50:55] Destroying room 2
[LOG       -- 06:50:55] Unable to process command! Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at ServerHub.Hub.Program.ProcessCommand(String comName, String[] comArgs) in D:\Projects\C#\BeatSaber\Source\BeatSaberMultiplayer-for-auros\ServerHub\Hub\Program.cs:line 587
```

**Comment by stewartgill1977** [comment]
Yep i get this to but it does work

**Comment by stewartgill1977** [comment]
I think it would be a lot better if it destroyed the empty room automatically when the last user leaves or it sees no users in the room.

**Comment by andruzzzhka** [comment]
this is how it works now, but sometimes if a user unexpectedly disconnects the room is not destroyed
