### ISSUE TITLE
Error occurred on trying to return to MP menu after song

### ISSUE THREAD

**Issue by jadeonking** [andruzzzhka/BeatSaberMultiplayer#52]
`[WARNING   -- 13:38:22] Socket exception occurred! System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at ServerHub.Rooms.RoomsController.GetRoomsListInBytes() in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Rooms\RoomsController.cs:line 175
   at ServerHub.Data.Client.ProcessPacket(BasePacket packet) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Data\Client.cs:line 310
   at ServerHub.Data.Client.ReceiveCallback(IAsyncResult ar) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Data\Client.cs:line 246`

After I was kicked from my own room from a server hub being run locally

**Comment by LunarTiger** [comment]
The same happened to me. I restarted the server and haven't seen it happen again though.
