### ISSUE TITLE
Linux Server Error

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#60]
Im playing with a Linux server 64bit and im getting this error any fix?

root@kali:~/server# cd
root@kali:~# chmod +x server
root@kali:~# cd server
root@kali:~/server# ./ServerHub

Unhandled Exception: System.InvalidOperationException: The terminfo database is invalid.
at System.TermInfo.Database..ctor(String term, Byte[] data)
at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
at System.TermInfo.Database.ReadDatabase(String term)
at System.TermInfo.Database.ReadActiveDatabase()
at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Lazy`1.CreateValue()
at System.ConsolePal.WriteResetColorString()
at System.ConsolePal.RefreshColors(ConsoleColor& toChange, ConsoleColor value)
at ServerHub.Misc.Logger.PrintLogMessage(LogMessage msg) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Misc\Logger.cs:line 81
at ServerHub.Misc.Logger.Exception(Object msg, Boolean hideHeader) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Misc\Logger.cs:line 68
Aborted
root@kali:~/server#

**Comment by andruzzzhka** [comment]
Try running it like this: `TERM=xterm ./ServerHub`

**Comment by stewartgill1977** [comment]
Thanks yep that works.

**Comment by stewartgill1977** [comment]
sorry im new to this Linux os for the server automatic restart on crash i see the script on the site and i understand to place it in the serverhub dir but what do i save the files as whats the extension type how do i make the files. thanks for your help.
